name: my_portfolio
version: 1.0.0+1
description: My Portfolio.
environment: 
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  get: ^4.6.1
  cupertino_icons: ^1.0.4
  animated_splash_screen: ^1.2.0
  flutter_spinkit: 5.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  url_strategy: 0.2.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

