name: my_portfolio
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.5.1
  flutter_spinkit: 5.1.0
  animated_splash_screen: 1.1.0
  cached_network_image: 3.2.0
  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "app_icon_round"
  ios: true
  image_path: "assets/icons/app_icon_round.png"

flutter: 
  uses-material-design: true

