name: my_portfolio
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.5.1
  animated_splash_screen: 1.1.0
  flutter_spinkit: 5.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  url_strategy: 0.2.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
    - assets/images/
  uses-material-design: true

